package org.assistix.proto.nativeapp.ui

import org.assistix.proto.nativeapp.ui.l10n.L10nBundle
import org.assistix.proto.nativeapp.ui.l10n.L10nData

/** UI strings for non-Compose code and legacy call sites. Updated via [setLanguage]. */
object UiStrings {
    private var bundle: L10nBundle = L10nData.en

    fun setLanguage(code: String) {
        bundle = L10nData.forCode(code)
    }

    val appName get() = bundle.appName
    val settings get() = bundle.settings
    val chats get() = bundle.chats
    val profile get() = bundle.profile
    val assistixAi get() = bundle.assistixAi
    val assistixAiTitle get() = bundle.assistixAiTitle
    val assistixAiSubtitle get() = bundle.assistixAiSubtitle
    val assistixChat get() = bundle.assistixChat
    val assistixTools get() = bundle.assistixTools
    val assistixModel get() = bundle.assistixModel
    val assistixSummarizeUnread get() = bundle.assistixSummarizeUnread
    val translateMessage get() = bundle.translateMessage
    val translateChat get() = bundle.translateChat
    val translateChatDone get() = bundle.translateChatDone
    val translateNothing get() = bundle.translateNothing
    val translateDone get() = bundle.translateDone
    val translatedLabel get() = bundle.translatedLabel
    val showOriginal get() = bundle.showOriginal
    val someoneRecording get() = bundle.someoneRecording
    val revokeOtherDevices get() = bundle.revokeOtherDevices
    val filterArchive get() = bundle.filterArchive
    val archiveFolderTitle get() = bundle.archiveFolderTitle
    val archivePullHint get() = bundle.archivePullHint
    val archivePullRelease get() = bundle.archivePullRelease
    val backFromArchive get() = bundle.backFromArchive
    fun archiveFolderCountFmt(count: Int): String = String.format(bundle.archiveFolderCountFmt, count)
    val filterMuted get() = bundle.filterMuted
    val filterDrafts get() = bundle.filterDrafts
    val filterStarred get() = bundle.filterStarred
    val filterGroups get() = bundle.filterGroups
    val filterPinned get() = bundle.filterPinned
    val filterNotes get() = bundle.filterNotes
    val filterVault get() = bundle.filterVault
    val autoTranslateChats get() = bundle.autoTranslateChats
    val assistixFixMessage get() = bundle.assistixFixMessage
    val assistixRewrite get() = bundle.assistixRewrite
    val assistixStyleNeutral get() = bundle.assistixStyleNeutral
    val assistixStyleFormal get() = bundle.assistixStyleFormal
    val assistixStyleFriendly get() = bundle.assistixStyleFriendly
    val assistixStyleShort get() = bundle.assistixStyleShort
    val assistixThinking get() = bundle.assistixThinking
    val assistixError get() = bundle.assistixError
    val assistixNotConfigured get() = bundle.assistixNotConfigured
    val assistixClearChat get() = bundle.assistixClearChat
    val assistixChatEmpty get() = bundle.assistixChatEmpty
    val assistixChatPlaceholder get() = bundle.assistixChatPlaceholder
    val assistixHint get() = bundle.assistixHint
    val assistixToolsChatHint get() = bundle.assistixToolsChatHint
    val language get() = bundle.language
    val darkTheme get() = bundle.darkTheme
    val signIn get() = bundle.signIn
    val createAccount get() = bundle.createAccount
    val signOut get() = bundle.signOut
    val logoutConfirmTitle get() = bundle.logoutConfirmTitle
    val logoutConfirmBody get() = bundle.logoutConfirmBody
    val searchNick get() = bundle.searchNick
    val newChat get() = bundle.newChat
    val message get() = bundle.message
    val encryptedHint get() = bundle.encryptedHint
    val send get() = bundle.send
    val edit get() = bundle.edit
    val delete get() = bundle.delete
    val forward get() = bundle.forward
    val copy get() = bundle.copy
    val react get() = bundle.react
    val save get() = bundle.save
    val cancel get() = bundle.cancel
    val close get() = bundle.close
    val download get() = bundle.download
    val openAttachment get() = bundle.openAttachment
    val forwardPickChat get() = bundle.forwardPickChat
    val forwarded get() = bundle.forwarded
    val forwardFailed get() = bundle.forwardFailed
    val forwardModeTitle get() = bundle.forwardModeTitle
    val forwardModeHint get() = bundle.forwardModeHint
    val deleteMessageTitle get() = bundle.deleteMessageTitle
    val deleteMessageOwnHint get() = bundle.deleteMessageOwnHint
    val deleteMessageOtherHint get() = bundle.deleteMessageOtherHint
    val nickCopied get() = bundle.nickCopied
    val nickChangeHint get() = bundle.nickChangeHint
    val folderColor get() = bundle.folderColor

    fun forwardModeSendFmt(count: Int): String = String.format(bundle.forwardModeSendFmt, count)

    fun forwardModeMessagesFmt(count: Int): String = String.format(bundle.forwardModeMessagesFmt, count)

    fun forwardPartialFmt(ok: Int, total: Int): String = String.format(bundle.forwardPartialFmt, ok, total)
    val shareModeTitle get() = bundle.shareModeTitle
    val shareModeHint get() = bundle.shareModeHint
    val sharedOk get() = bundle.sharedOk
    val shareFailed get() = bundle.shareFailed

    fun shareModeSendFmt(count: Int): String = String.format(bundle.shareModeSendFmt, count)

    fun shareModeImagesFmt(count: Int): String = String.format(bundle.shareModeImagesFmt, count)

    fun sharePartialFmt(ok: Int, total: Int): String = String.format(bundle.sharePartialFmt, ok, total)
    val uploadFailed get() = bundle.uploadFailed
    val savedMessages get() = bundle.savedMessages
    val saveToSaved get() = bundle.saveToSaved
    val savedTo get() = bundle.savedTo
    val downloadFailed get() = bundle.downloadFailed
    val editFailed get() = bundle.editFailed
    val noMessages get() = bundle.noMessages
    val edited get() = bundle.edited
    val incomingCall get() = bundle.incomingCall
    val outgoingCall get() = bundle.outgoingCall
    val videoCall get() = bundle.videoCall
    val audioCall get() = bundle.audioCall
    val callMissed get() = bundle.callMissed
    val callCancelled get() = bundle.callCancelled
    val callDeclined get() = bundle.callDeclined
    val openLinkTitle get() = bundle.openLinkTitle
    val openLinkBody get() = bundle.openLinkBody
    val openLinkOpen get() = bundle.openLinkOpen
    val copyLink get() = bundle.copyLink
    val maxPins get() = bundle.maxPins
    val notifyMentionsOnly get() = bundle.notifyMentionsOnly
    val cacheClearedReload get() = bundle.cacheClearedReload
    val chatExport get() = bundle.chatExport
    val assistixRenameThread get() = bundle.assistixRenameThread
    fun assistixSelectedFmt(count: Int) = bundle.assistixSelectedFmt.format(count)
    val profileShareLink get() = bundle.profileShareLink
    val profileSectionPreview get() = bundle.profileSectionPreview
    val profileSectionIdentity get() = bundle.profileSectionIdentity
    val profileSectionAccount get() = bundle.profileSectionAccount
    val profileSectionStatus get() = bundle.profileSectionStatus
    val profileSectionAbout get() = bundle.profileSectionAbout
    val profileSectionShare get() = bundle.profileSectionShare
    val profilePreviewHint get() = bundle.profilePreviewHint
    val profileAvatarHint get() = bundle.profileAvatarHint
    val profileEmailLabel get() = bundle.profileEmailLabel
    val profileEmailHint get() = bundle.profileEmailHint
    val profileStatusPlaceholder get() = bundle.profileStatusPlaceholder
    val profileBioPlaceholder get() = bundle.profileBioPlaceholder
    val profileLoadRetry get() = bundle.profileLoadRetry
    val profileUnsaved get() = bundle.profileUnsaved
    val profileWriteMessage get() = bundle.profileWriteMessage
    val profileTabCard get() = bundle.profileTabCard
    val profileTabEdit get() = bundle.profileTabEdit
    val profileCompleteness get() = bundle.profileCompleteness
    val profileCompletenessHint get() = bundle.profileCompletenessHint
    val profileQrSubtitle get() = bundle.profileQrSubtitle
    val profileTapChange get() = bundle.profileTapChange
    val voiceInput get() = bundle.voiceInput
    val qrHubTitle get() = bundle.qrHubTitle
    val qrHubHint get() = bundle.qrHubHint
    val qrHubScan get() = bundle.qrHubScan
    val qrHubMyCode get() = bundle.qrHubMyCode
    val chatMultiPin get() = bundle.chatMultiPin
    val chatMultiMute get() = bundle.chatMultiMute
    val chatMultiUnmute get() = bundle.chatMultiUnmute
    val chatMultiLock get() = bundle.chatMultiLock
    val chatMultiArchive get() = bundle.chatMultiArchive
    val chatMultiUnarchive get() = bundle.chatMultiUnarchive
    val chatMultiMarkRead get() = bundle.chatMultiMarkRead
    val shareMessage get() = bundle.shareMessage
    val newMessagesDivider get() = bundle.newMessagesDivider
    val starMessage get() = bundle.starMessage
    val unstarMessage get() = bundle.unstarMessage
    val chatMenuShowStarred get() = bundle.chatMenuShowStarred
    val chatMenuShowAllMessages get() = bundle.chatMenuShowAllMessages
    val composerDraftSaved get() = bundle.composerDraftSaved
    val clearComposerDraft get() = bundle.clearComposerDraft
    val jumpToStarred get() = bundle.jumpToStarred
    val exportChat get() = bundle.exportChat
    fun exportChatSubjectFmt(title: String) = bundle.exportChatSubjectFmt.format(title)
    val exportChatMeLabel get() = bundle.exportChatMeLabel
    val exportChatEmpty get() = bundle.exportChatEmpty
    val editChatNote get() = bundle.editChatNote
    val chatNotePlaceholder get() = bundle.chatNotePlaceholder
    val clearAllStars get() = bundle.clearAllStars
    val scrollToTop get() = bundle.scrollToTop
    val settingsVoiceSpeed get() = bundle.settingsVoiceSpeed
    val settingsSortUnreadFirst get() = bundle.settingsSortUnreadFirst
    fun chatMessageCountFmt(n: Int) = bundle.chatMessageCountFmt.format(n)
    fun chatStarredCountFmt(stars: Int, messages: Int) = bundle.chatStarredCountFmt.format(stars, messages)
    val copyTimestamp get() = bundle.copyTimestamp
    val clearChatNote get() = bundle.clearChatNote
    fun markAllReadDoneFmt(n: Int) = bundle.markAllReadDoneFmt.format(n)
    val chatsFilterEmptyTitle get() = bundle.chatsFilterEmptyTitle
    val chatsFilterEmptyBody get() = bundle.chatsFilterEmptyBody
    val chatsFilterEmptyAction get() = bundle.chatsFilterEmptyAction
    fun voiceSpeedLabelFmt(idx: Int) =
        when (idx.coerceIn(0, 2)) {
            1 -> "1.5×"
            2 -> "2×"
            else -> "1×"
        }
    val chatMultiUnlock get() = bundle.chatMultiUnlock
    fun chatSelectedFmt(n: Int) = bundle.chatSelectedFmt.format(n)
    val msgSelectAll get() = bundle.msgSelectAll

    fun msgSelectedFmt(count: Int): String = String.format(bundle.msgSelectedFmt, count)
    val msgDeselectAll get() = bundle.msgDeselectAll
    fun msgDeleteBulkHint(n: Int) = bundle.msgDeleteBulkHint.format(n)
    fun deleteForMeCountFmt(n: Int) = bundle.deleteForMeCountFmt.format(n)
    fun deleteForAllCountFmt(n: Int) = bundle.deleteForAllCountFmt.format(n)
    val msgActionSaveShort get() = bundle.msgActionSaveShort
    val msgActionReportShort get() = bundle.msgActionReportShort
    val pinMessage get() = bundle.pinMessage
    val unpinMessage get() = bundle.unpinMessage
    val pinnedMessage get() = bundle.pinnedMessage
    val shareGroupLink get() = bundle.shareGroupLink
    val shareChannelLink get() = bundle.shareChannelLink
    val enterVaultPin get() = bundle.enterVaultPin
    val vaultPinSet get() = bundle.vaultPinSet
    val vaultUnlockTitle get() = bundle.vaultUnlockTitle
    val vaultWrongPin get() = bundle.vaultWrongPin
    val unlock get() = bundle.unlock
    val inviteJoined get() = bundle.inviteJoined
    val share get() = bundle.share
    val appVersionFmt get() = bundle.appVersionFmt
    val deleteForMe get() = bundle.deleteForMe
    val deleteForAll get() = bundle.deleteForAll
    val deleteMessageConfirm get() = bundle.deleteMessageConfirm
    val assistixSummarizeChat get() = bundle.assistixSummarizeChat
    val assistixComposerTitle get() = bundle.assistixComposerTitle
    val assistixSmartReplies get() = bundle.assistixSmartReplies
    val assistixExtractTasks get() = bundle.assistixExtractTasks
    val assistixExpandDraft get() = bundle.assistixExpandDraft
    val assistixToneCheck get() = bundle.assistixToneCheck
    val assistixAskChat get() = bundle.assistixAskChat
    val assistixAskHint get() = bundle.assistixAskHint
    val assistixExplain get() = bundle.assistixExplain
    val assistixSummarizeVoice get() = bundle.assistixSummarizeVoice
    val assistixSavedSuggestTags get() = bundle.assistixSavedSuggestTags
    val assistixCopyResult get() = bundle.assistixCopyResult
    val assistixInsertDraft get() = bundle.assistixInsertDraft
    val assistixSummarizeSelection get() = bundle.assistixSummarizeSelection
    val voiceSearchHint get() = bundle.voiceSearchHint
    val savedAddTag get() = bundle.savedAddTag
    val savedTagHint get() = bundle.savedTagHint
    val savedTagSaved get() = bundle.savedTagSaved
    val savedSetReminder get() = bundle.savedSetReminder
    val savedReminderHint get() = bundle.savedReminderHint
    val savedReminderSaved get() = bundle.savedReminderSaved
    val savedExportNotes get() = bundle.savedExportNotes
    val widgetAiBriefTitle get() = bundle.widgetAiBriefTitle
    val widgetAiBriefLoading get() = bundle.widgetAiBriefLoading
    val widgetAllRead get() = bundle.widgetAllRead
    val widgetOpenApp get() = bundle.widgetOpenApp
    val searchPrev get() = bundle.searchPrev
    val searchNext get() = bundle.searchNext
    val smartSavedAll get() = bundle.smartSavedAll
    val smartSavedLinks get() = bundle.smartSavedLinks
    val smartSavedMedia get() = bundle.smartSavedMedia
    val smartSavedVoice get() = bundle.smartSavedVoice
    val albumNeedTwo get() = bundle.albumNeedTwo
    val newFolder get() = bundle.newFolder
    val folderName get() = bundle.folderName
    val folderSave get() = bundle.folderSave
    val folderPickChats get() = bundle.folderPickChats
    val foldersSection get() = bundle.foldersSection
    val folderEdit get() = bundle.folderEdit
    val folderDelete get() = bundle.folderDelete
    val folderMoveUp get() = bundle.folderMoveUp
    val folderMoveDown get() = bundle.folderMoveDown
    val folderEmpty get() = bundle.folderEmpty
    val assistixRateLimited get() = bundle.assistixRateLimited
    val mediaSendPreview get() = bundle.mediaSendPreview
    val mediaSendConfirm get() = bundle.mediaSendConfirm
    val mediaReplace get() = bundle.mediaReplace
    val voiceTrimHint get() = bundle.voiceTrimHint
    val voiceTrimStart get() = bundle.voiceTrimStart
    val voiceTrimEnd get() = bundle.voiceTrimEnd
    val accept get() = bundle.accept

    fun callDurationLabel(durationSec: Int): String {
        val sec = durationSec.coerceAtLeast(0)
        val m = sec / 60
        val s = sec % 60
        return String.format("%d:%02d", m, s)
    }
    val decline get() = bundle.decline
    val endCall get() = bundle.endCall
    val connecting get() = bundle.connecting
    val connected get() = bundle.connected
    val waitingAnswer get() = bundle.waitingAnswer
    val displayName get() = bundle.displayName
    val displayNameRequired get() = bundle.displayNameRequired
    val bio get() = bundle.bio
    val status get() = bundle.status
    val username get() = bundle.username
    val email get() = bundle.email
    val editProfile get() = bundle.editProfile
    val viewProfile get() = bundle.viewProfile
    val profileLoadFailed get() = bundle.profileLoadFailed
    val changePhoto get() = bundle.changePhoto
    val profileSaved get() = bundle.profileSaved
    val saveFailed get() = bundle.saveFailed
    val avatarUpdated get() = bundle.avatarUpdated
    val online get() = bundle.online
    val lastSeenUnknown get() = bundle.lastSeenUnknown
    val lastSeenMinutes get() = bundle.lastSeenMinutes
    val lastSeenHours get() = bundle.lastSeenHours
    val lastSeenAt get() = bundle.lastSeenAt
    val typing get() = bundle.typing
    val holdToRecord get() = bundle.holdToRecord
    val slideToCancel get() = bundle.slideToCancel
    val slideToCancelArmed get() = bundle.slideToCancelArmed
    val releaseToSend get() = bundle.releaseToSend
    val slideUpToLock get() = bundle.slideUpToLock
    val recordLocked get() = bundle.recordLocked
    val tapToStopRecord get() = bundle.tapToStopRecord
    val swipeMarkRead get() = bundle.swipeMarkRead
    val swipeArchive get() = bundle.swipeArchive
    val swipeUnarchive get() = bundle.swipeUnarchive
    val signingOut get() = bundle.signingOut
    val fabRecentChats get() = bundle.fabRecentChats

    fun offlineQueuedFmt(count: Int): String = String.format(bundle.offlineQueuedFmt, count)

    fun onlineQueuedFmt(count: Int): String = String.format(bundle.onlineQueuedFmt, count)

    val peerAnsweredConnecting get() = bundle.peerAnsweredConnecting

    fun shareImagesFmt(count: Int): String = String.format(bundle.shareImagesFmt, count)
    val voiceMessage get() = bundle.voiceMessage
    val attach get() = bundle.attach
    val call get() = bundle.call
    val video get() = bundle.video
    val videoComingSoon get() = bundle.videoComingSoon
    val welcomeSubtitle get() = bundle.welcomeSubtitle
    val nickOrEmail get() = bundle.nickOrEmail
    val nick get() = bundle.nick
    val password get() = bundle.password
    val emailOptional get() = bundle.emailOptional
    val emailRequired get() = bundle.emailRequired
    val verifyEmailTitle get() = bundle.verifyEmailTitle
    val verifyEmailHint get() = bundle.verifyEmailHint
    val verifyEmailMissingUserId get() = bundle.verifyEmailMissingUserId
    val verifyEmailRequiredTitle get() = bundle.verifyEmailRequiredTitle
    val verifyEmailRequiredBanner get() = bundle.verifyEmailRequiredBanner
    val verificationCodeTooShort get() = bundle.verificationCodeTooShort
    val verificationCode get() = bundle.verificationCode
    val resendCode get() = bundle.resendCode
    val forgotPassword get() = bundle.forgotPassword
    val forgotPasswordTitle get() = bundle.forgotPasswordTitle
    val forgotPasswordHint get() = bundle.forgotPasswordHint
    val forgotPasswordDone get() = bundle.forgotPasswordDone
    val confirm get() = bundle.confirm
    val policyConsent get() = bundle.policyConsent
    val policyLinkPrivacy get() = bundle.policyLinkPrivacy
    val policyLinkRules get() = bundle.policyLinkRules
    val policyMustAccept get() = bundle.policyMustAccept
    val legalSection get() = bundle.legalSection
    val openPrivacyPolicy get() = bundle.openPrivacyPolicy
    val openRules get() = bundle.openRules
    val reportTitle get() = bundle.reportTitle
    val reportHint get() = bundle.reportHint
    val reportReasonProfile get() = bundle.reportReasonProfile
    val reportReasonSpam get() = bundle.reportReasonSpam
    val reportReasonAbuse get() = bundle.reportReasonAbuse
    val reportReasonIllegal get() = bundle.reportReasonIllegal
    val reportReasonOther get() = bundle.reportReasonOther
    val reportSelectMessages get() = bundle.reportSelectMessages
    val reportSelectMessagesInChat get() = bundle.reportSelectMessagesInChat
    val reportProfileNoMessagesHint get() = bundle.reportProfileNoMessagesHint
    val reportMessagesSelected get() = bundle.reportMessagesSelected
    val reportDetailsOptional get() = bundle.reportDetailsOptional
    val reportSubmit get() = bundle.reportSubmit
    val reportUserAction get() = bundle.reportUserAction
    val reportMessageTitle get() = bundle.reportMessageTitle
    val reportMessageHint get() = bundle.reportMessageHint
    val reportMessageAction get() = bundle.reportMessageAction
    val chatMenuMore get() = bundle.chatMenuMore
    val chatMenuVideoCall get() = bundle.chatMenuVideoCall
    val chatMenuWallpaper get() = bundle.chatMenuWallpaper
    val chatMenuClearHistory get() = bundle.chatMenuClearHistory
    val chatMenuDeleteChat get() = bundle.chatMenuDeleteChat
    val confirmClearHistoryTitle get() = bundle.confirmClearHistoryTitle
    val confirmClearHistoryBody get() = bundle.confirmClearHistoryBody
    val confirmDeleteChatTitle get() = bundle.confirmDeleteChatTitle
    val confirmDeleteChatBody get() = bundle.confirmDeleteChatBody
    val callParticipantsTitle get() = bundle.callParticipantsTitle
    val blockUserTitle get() = bundle.blockUserTitle
    val blockUserConfirm get() = bundle.blockUserConfirm
    val blockUserAction get() = bundle.blockUserAction
    val userBlockedDone get() = bundle.userBlockedDone
    val suspensionTitle get() = bundle.suspensionTitle
    val suspensionReason get() = bundle.suspensionReason
    val suspensionUntil get() = bundle.suspensionUntil
    val suspensionNoAppeal get() = bundle.suspensionNoAppeal
    val suspensionIsolation get() = bundle.suspensionIsolation
    val profileShameTitle get() = bundle.profileShameTitle
    val profileShameDefault get() = bundle.profileShameDefault
    val privateMarkLabel get() = bundle.privateMarkLabel
    val plainTextLabel get() = bundle.plainTextLabel
    val privateMarkHint get() = bundle.privateMarkHint
    val privateMessagePreview get() = bundle.privateMessagePreview
    val privateMarkDisclaimer get() = bundle.privateMarkDisclaimer
    val authHubTitle get() = bundle.authHubTitle
    val authHubSubtitle get() = bundle.authHubSubtitle
    val authNewAccount get() = bundle.authNewAccount
    val authHaveAccount get() = bundle.authHaveAccount
    val regEmailStepTitle get() = bundle.regEmailStepTitle
    val regEmailStepBody get() = bundle.regEmailStepBody
    val regPasswordStepTitle get() = bundle.regPasswordStepTitle
    val regPasswordStepBody get() = bundle.regPasswordStepBody
    val regPasswordConfirmTitle get() = bundle.regPasswordConfirmTitle
    val regPasswordConfirmBody get() = bundle.regPasswordConfirmBody
    val regNickStepTitle get() = bundle.regNickStepTitle
    val regNickStepBody get() = bundle.regNickStepBody
    val regNickSuggested get() = bundle.regNickSuggested
    fun regNickUseSuggestedFmt(nick: String): String = bundle.regNickUseSuggestedFmt.format(nick)
    val regNickAvailable get() = bundle.regNickAvailable
    val regNickTaken get() = bundle.regNickTaken
    val regDisplayStepTitle get() = bundle.regDisplayStepTitle
    val regDisplayStepBody get() = bundle.regDisplayStepBody
    val regPolicyStepTitle get() = bundle.regPolicyStepTitle
    val regPolicyStepBody get() = bundle.regPolicyStepBody
    val regPasswordConfirmField get() = bundle.regPasswordConfirmField
    val regVerifyLaterHint get() = bundle.regVerifyLaterHint
    val regSendCode get() = bundle.regSendCode
    val onboardPolicyTitle get() = bundle.onboardPolicyTitle
    val onboardPolicyBody get() = bundle.onboardPolicyBody
    val passwordMismatch get() = bundle.passwordMismatch
    val passwordTooShort get() = bundle.passwordTooShort
    val nickInvalid get() = bundle.nickInvalid
    val createAccountWizardTitle get() = bundle.createAccountWizardTitle
    val groupsNoCalls get() = bundle.groupsNoCalls
    val signInTitle get() = bundle.signInTitle
    val registerTitle get() = bundle.registerTitle
    val back get() = bundle.back
    val genericError get() = bundle.genericError
    val signInFailed get() = bundle.signInFailed
    val emptyToken get() = bundle.emptyToken
    val networkUnavailable get() = bundle.networkUnavailable
    val serverNotJson get() = bundle.serverNotJson
    val apiHostMisconfigured get() = bundle.apiHostMisconfigured
    val newMessage get() = bundle.newMessage
    val chatDefault get() = bundle.chatDefault
    val file get() = bundle.file
    val settingsTitle get() = bundle.settings
    val messagesCached get() = bundle.messagesCached
    val callsWebRtc get() = bundle.callsWebRtc
    val callError get() = bundle.callError
    val answering get() = bundle.answering
    val msgChannel get() = bundle.msgChannel
    val msgChannelDesc get() = bundle.msgChannelDesc
    val callChannel get() = bundle.callChannel
    val callChannelDesc get() = bundle.callChannelDesc
    val skip get() = bundle.skip
    val next get() = bundle.next
    val getStarted get() = bundle.getStarted
    val becomePartOfProto get() = bundle.becomePartOfProto
    val welcomeTagline get() = bundle.welcomeTagline
    val messageNotifications get() = bundle.messageNotifications
    val callNotifications get() = bundle.callNotifications
    val readReceiptsSetting get() = bundle.readReceiptsSetting
    val typingIndicatorsSetting get() = bundle.typingIndicatorsSetting
    val autoDownloadMedia get() = bundle.autoDownloadMedia
    val textSize get() = bundle.textSize
    val reduceMotion get() = bundle.reduceMotion
    val appearance get() = bundle.appearance
    val notifications get() = bundle.notifications
    val privacy get() = bundle.privacy
    val chatSettings get() = bundle.chatSettings
    val play get() = bundle.play
    val pause get() = bundle.pause
    val voiceNote get() = bundle.voiceNote
    val transcribe get() = bundle.transcribe
    val sttFailed get() = bundle.sttFailed
    val sttOfflineOnly get() = bundle.sttOfflineOnly
    val sttServerBusy get() = bundle.sttServerBusy
    val sttLocalBusy get() = bundle.sttLocalBusy
    val sttPhaseListening get() = bundle.sttPhaseListening
    val sttPhaseWriting get() = bundle.sttPhaseWriting
    val sttAutoQueued get() = bundle.sttAutoQueued
    val sttSettings get() = bundle.sttSettings
    val sttPackHint get() = bundle.sttPackHint
    val sttPackReady get() = bundle.sttPackReady
    val sttPackDownloading get() = bundle.sttPackDownloading
    val sttPackMissing get() = bundle.sttPackMissing
    val sttOfflineEnabled get() = bundle.sttOfflineEnabled
    val sttDeviceOnly get() = bundle.sttDeviceOnly
    val sttServerFirstHint get() = bundle.sttServerFirstHint
    val sttModelPickTitle get() = bundle.sttModelPickTitle
    val sttModelPickBody get() = bundle.sttModelPickBody
    val sttModelLite get() = bundle.sttModelLite
    val sttModelMedium get() = bundle.sttModelMedium
    val sttModelPowerful get() = bundle.sttModelPowerful
    val sttModelRecommended get() = bundle.sttModelRecommended
    val sttModelLiteDesc get() = bundle.sttModelLiteDesc
    val sttModelMediumDesc get() = bundle.sttModelMediumDesc
    val sttModelPowerfulDesc get() = bundle.sttModelPowerfulDesc
    val sttModelRecommendedForDevice get() = bundle.sttModelRecommendedForDevice
    val sttModelPowerfulWarningTitle get() = bundle.sttModelPowerfulWarningTitle
    val sttModelPowerfulWarningBody get() = bundle.sttModelPowerfulWarningBody
    val sttModelPowerfulConfirm get() = bundle.sttModelPowerfulConfirm
    val profileNickTapCopy get() = bundle.profileNickTapCopy
    val sttModelSizeLite get() = bundle.sttModelSizeLite
    val sttModelSizeMedium get() = bundle.sttModelSizeMedium
    val sttModelSizePowerful get() = bundle.sttModelSizePowerful
    val sttDownloadPack get() = bundle.sttDownloadPack
    val sttDeletePack get() = bundle.sttDeletePack
    val sttSliderFast get() = bundle.sttSliderFast
    val sttSliderPowerful get() = bundle.sttSliderPowerful
    val storagePersistentHint get() = bundle.storagePersistentHint
    val dataStorageTitle get() = bundle.dataStorageTitle
    val dataStorageHint get() = bundle.dataStorageHint
    val dataStorageTotal get() = bundle.dataStorageTotal
    val dataStoragePath get() = bundle.dataStoragePath
    val dataStorageDb get() = bundle.dataStorageDb
    val dataStorageCache get() = bundle.dataStorageCache
    val dataStorageStt get() = bundle.dataStorageStt
    val dataStoragePrefs get() = bundle.dataStoragePrefs
    val dataStorageBackups get() = bundle.dataStorageBackups
    val dataStoragePermissionHint get() = bundle.dataStoragePermissionHint
    val dataStorageGrantAccess get() = bundle.dataStorageGrantAccess
    val dataStorageOpenFolder get() = bundle.dataStorageOpenFolder
    val settingsDataStorage get() = bundle.settingsDataStorage
    val sttWifiOnlyHeavy get() = bundle.sttWifiOnlyHeavy
    val sttWifiOnlyHeavyHint get() = bundle.sttWifiOnlyHeavyHint
    val sttOnlyWhenCharging get() = bundle.sttOnlyWhenCharging
    val sttOnlyWhenChargingHint get() = bundle.sttOnlyWhenChargingHint
    val sttMaxQueueLabel get() = bundle.sttMaxQueueLabel
    val sttMaxQueueHint get() = bundle.sttMaxQueueHint
    val sttBadgeLocal get() = bundle.sttBadgeLocal
    val sttBadgeServer get() = bundle.sttBadgeServer
    val sttCopyTranscript get() = bundle.sttCopyTranscript
    val sttTranslateTranscript get() = bundle.sttTranslateTranscript
    val sttPackReadyNotificationTitle get() = bundle.sttPackReadyNotificationTitle
    val sttPackReadyNotificationBody get() = bundle.sttPackReadyNotificationBody
    val sttDownloadWifiBlocked get() = bundle.sttDownloadWifiBlocked
    val onboardSttTitle get() = bundle.onboardSttTitle
    val onboardSttBody get() = bundle.onboardSttBody
    val sttTier0Eta get() = bundle.sttTier0Eta
    val sttTier1Eta get() = bundle.sttTier1Eta
    val sttTier2Eta get() = bundle.sttTier2Eta
    val sttTier3Eta get() = bundle.sttTier3Eta
    val sttTier4Eta get() = bundle.sttTier4Eta
    val sttTier5Eta get() = bundle.sttTier5Eta
    val sttTier0Title get() = bundle.sttTier0Title
    val sttTier1Title get() = bundle.sttTier1Title
    val sttTier2Title get() = bundle.sttTier2Title
    val sttTier3Title get() = bundle.sttTier3Title
    val sttTier4Title get() = bundle.sttTier4Title
    val sttTier5Title get() = bundle.sttTier5Title
    val sttTier0Desc get() = bundle.sttTier0Desc
    val sttTier1Desc get() = bundle.sttTier1Desc
    val sttTier2Desc get() = bundle.sttTier2Desc
    val sttTier3Desc get() = bundle.sttTier3Desc
    val sttTier4Desc get() = bundle.sttTier4Desc
    val sttTier5Desc get() = bundle.sttTier5Desc
    val sttTier0Size get() = bundle.sttTier0Size
    val sttTier1Size get() = bundle.sttTier1Size
    val sttTier2Size get() = bundle.sttTier2Size
    val sttTier3Size get() = bundle.sttTier3Size
    val sttTier4Size get() = bundle.sttTier4Size
    val sttTier5Size get() = bundle.sttTier5Size
    val sttModelsInstalledFmt get() = bundle.sttModelsInstalledFmt
    val sttModelHeavyWarningFmt get() = bundle.sttModelHeavyWarningFmt
    val videoMessage get() = bundle.videoMessage
    val mute get() = bundle.mute
    val unmute get() = bundle.unmute
    val speaker get() = bundle.speaker
    val peerMuted get() = bundle.peerMuted
    val flipCamera get() = bundle.flipCamera
    val statusEmoji get() = bundle.statusEmoji
    val statusEmojiPick get() = bundle.statusEmojiPick
    val scrollToBottom get() = bundle.scrollToBottom
    val readAt get() = bundle.readAt
    val unread get() = bundle.unread
    val onboardingAiTitle get() = bundle.onboardingAiTitle
    val onboardingAiBody get() = bundle.onboardingAiBody
    val onboardWhatTitle get() = bundle.onboardWhatTitle
    val onboardWhatBody get() = bundle.onboardWhatBody
    val onboardSecurityTitle get() = bundle.onboardSecurityTitle
    val onboardSecurityBody get() = bundle.onboardSecurityBody
    val onboardCleanTitle get() = bundle.onboardCleanTitle
    val onboardCleanBody get() = bundle.onboardCleanBody
    val onboardChatsTitle get() = bundle.onboardChatsTitle
    val onboardChatsBody get() = bundle.onboardChatsBody
    val onboardCallsTitle get() = bundle.onboardCallsTitle
    val onboardCallsBody get() = bundle.onboardCallsBody
    val onboardWelcomeTitle get() = bundle.onboardWelcomeTitle
    val onboardWelcomeSubtitle get() = bundle.onboardWelcomeSubtitle
    val onboardPickLanguage get() = bundle.onboardPickLanguage
    val onboardSetupTitle get() = bundle.onboardSetupTitle
    val onboardSetupSubtitle get() = bundle.onboardSetupSubtitle
    val onboardThemeLight get() = bundle.onboardThemeLight
    val onboardThemeSystem get() = bundle.onboardThemeSystem
    val onboardMediaTitle get() = bundle.onboardMediaTitle
    val onboardMediaBody get() = bundle.onboardMediaBody
    val onboardBadgePrivate get() = bundle.onboardBadgePrivate
    val onboardBadgeSecure get() = bundle.onboardBadgeSecure
    val onboardBadgeFast get() = bundle.onboardBadgeFast
    val newGroup get() = bundle.newGroup
    val groupTitle get() = bundle.groupTitle
    val addMembers get() = bundle.addMembers
    val createGroup get() = bundle.createGroup
    val groupInfo get() = bundle.groupInfo
    val renameGroup get() = bundle.renameGroup
    val leaveGroup get() = bundle.leaveGroup
    val roleOwner get() = bundle.roleOwner
    val roleAdmin get() = bundle.roleAdmin
    val roleMember get() = bundle.roleMember
    val makeAdmin get() = bundle.makeAdmin
    val removeAdmin get() = bundle.removeAdmin
    val manageRole get() = bundle.manageRole
    val permissionDenied get() = bundle.permissionDenied
    val memberAdded get() = bundle.memberAdded
    val groupNeedTitleMembers get() = bundle.groupNeedTitleMembers
    val groupCreateFailed get() = bundle.groupCreateFailed
    val remove get() = bundle.remove
    val newDm get() = bundle.newDm
    val playbackSpeed get() = bundle.playbackSpeed

    fun selectedMembers(count: Int): String = String.format(bundle.selectedMembersFmt, count)

    fun groupMembersCount(count: Int): String = String.format(bundle.groupMembersCountFmt, count)

    val settingsAccount get() = bundle.settingsAccount
    val settingsSecurity get() = bundle.settingsSecurity
    val settingsCallsMedia get() = bundle.settingsCallsMedia
    val settingsData get() = bundle.settingsData
    val settingsChatsSection get() = bundle.settingsChatsSection
    val settingsLinkPreviews get() = bundle.settingsLinkPreviews
    val settingsCompactChatList get() = bundle.settingsCompactChatList
    val settingsSendOnEnter get() = bundle.settingsSendOnEnter
    val settingsHapticFeedback get() = bundle.settingsHapticFeedback
    val settingsNetworkSection get() = bundle.settingsNetworkSection
    val settingsNetworkHint get() = bundle.settingsNetworkHint
    val settingsAssistixSection get() = bundle.settingsAssistixSection
    val settingsAssistixProtoHint get() = bundle.settingsAssistixProtoHint
    val settingsAssistixModelHint get() = bundle.settingsAssistixModelHint
    val settingsGdprSection get() = bundle.settingsGdprSection
    val settingsGdprBody get() = bundle.settingsGdprBody
    val settingsExportData get() = bundle.settingsExportData
    val settingsExporting get() = bundle.settingsExporting
    val settingsExportSavedFmt get() = bundle.settingsExportSavedFmt
    val settingsDeleteAccount get() = bundle.settingsDeleteAccount
    val settingsDeleteAccountTitle get() = bundle.settingsDeleteAccountTitle
    val settingsDeleteAccountBody get() = bundle.settingsDeleteAccountBody
    val settingsDeleteConfirm get() = bundle.settingsDeleteConfirm
    val supportEmail get() = bundle.supportEmail
    val langNativeEn get() = bundle.langNativeEn
    val langNativeRu get() = bundle.langNativeRu
    val langNativeIt get() = bundle.langNativeIt
    val langLabelEn get() = bundle.langLabelEn
    val langLabelRu get() = bundle.langLabelRu
    val langLabelIt get() = bundle.langLabelIt
    val postRegTourWelcome get() = bundle.postRegTourWelcome
    val postRegTourSkip get() = bundle.postRegTourSkip
    val postRegTourNext get() = bundle.postRegTourNext
    val postRegTourDone get() = bundle.postRegTourDone
    val postRegTourChatsTitle get() = bundle.postRegTourChatsTitle
    val postRegTourChatsBody get() = bundle.postRegTourChatsBody
    val postRegTourNewChatTitle get() = bundle.postRegTourNewChatTitle
    val postRegTourNewChatBody get() = bundle.postRegTourNewChatBody
    val postRegTourFabTitle get() = bundle.postRegTourFabTitle
    val postRegTourFabBody get() = bundle.postRegTourFabBody
    val postRegTourQrTitle get() = bundle.postRegTourQrTitle
    val postRegTourQrBody get() = bundle.postRegTourQrBody
    val postRegTourNotifTitle get() = bundle.postRegTourNotifTitle
    val postRegTourNotifBody get() = bundle.postRegTourNotifBody
    val postRegTourSettingsTitle get() = bundle.postRegTourSettingsTitle
    val postRegTourSettingsBody get() = bundle.postRegTourSettingsBody
    val widgetLoggedOutHint get() = bundle.widgetLoggedOutHint
    val widgetNoActiveChats get() = bundle.widgetNoActiveChats
    val widgetMessengerTagline get() = bundle.widgetMessengerTagline
    val settingsHelpSection get() = bundle.settingsHelpSection
    val settingsReplayOnboardingHint get() = bundle.settingsReplayOnboardingHint
    val settingsAbout get() = bundle.settingsAbout
    val settingsAboutBody get() = bundle.settingsAboutBody

    fun settingsVersion(version: String): String = String.format(bundle.settingsVersionFmt, version)

    val settingsUpdates get() = bundle.settingsUpdates
    val updateAutoBackground get() = bundle.updateAutoBackground
    val updateAutoBackgroundHint get() = bundle.updateAutoBackgroundHint
    val updateChecking get() = bundle.updateChecking
    val updateUpToDate get() = bundle.updateUpToDate
    val updateTapCheck get() = bundle.updateTapCheck
    val updateCheckNow get() = bundle.updateCheckNow
    val updateDownloading get() = bundle.updateDownloading
    val updateReadyInstall get() = bundle.updateReadyInstall
    val updateDownloadFailed get() = bundle.updateDownloadFailed
    val updateCheckFailed get() = bundle.updateCheckFailed
    val updateDownload get() = bundle.updateDownload
    val updateInstall get() = bundle.updateInstall
    val updateLater get() = bundle.updateLater
    val updateDialogBody get() = bundle.updateDialogBody
    val updateAllowInstall get() = bundle.updateAllowInstall

    fun updateAvailableFmt(version: String): String = String.format(bundle.updateAvailableFmt, version)

    fun updateDownloadingProgress(percent: Int): String = String.format(bundle.updateDownloadingProgressFmt, percent)

    fun updateDialogTitle(version: String): String = String.format(bundle.updateDialogTitleFmt, version)

    fun updateDownloadVersion(version: String): String = String.format(bundle.updateDownloadVersionFmt, version)

    val updateNotifChannelName get() = bundle.updateNotifChannelName
    val updateNotifChannelDesc get() = bundle.updateNotifChannelDesc
    val updateMandatoryShort get() = bundle.updateMandatoryShort
    val updateOpenApp get() = bundle.updateOpenApp

    val updateAvailableBody get() = bundle.updateAvailableBody
    val updateReadyBody get() = bundle.updateReadyBody

    fun updateAvailableTitle(version: String): String = String.format(bundle.updateAvailableTitleFmt, version)

    fun updateReadyTitle(version: String): String = String.format(bundle.updateReadyTitleFmt, version)

    fun fabDevicesBadge(count: Int): String = String.format(bundle.fabDevicesBadgeFmt, count)

    fun updateMandatoryTitle(version: String): String = String.format(bundle.updateMandatoryTitleFmt, version)

    val updateMandatoryNoSkip get() = bundle.updateMandatoryNoSkip

    val updateMandatoryPreparing get() = bundle.updateMandatoryPreparing

    fun updateMandatoryDefaultBody(version: String): String =
        String.format(bundle.updateMandatoryDefaultBodyFmt, version)

    val updateMandatoryHelpTitle get() = bundle.updateMandatoryHelpTitle
    val updateMandatoryHelpErrorHint get() = bundle.updateMandatoryHelpErrorHint
    val updateMandatoryHelpStep1 get() = bundle.updateMandatoryHelpStep1
    val updateMandatoryHelpStep2 get() = bundle.updateMandatoryHelpStep2
    val updateMandatoryHelpStep3 get() = bundle.updateMandatoryHelpStep3
    val updateMandatoryHelpDownloadBtn get() = bundle.updateMandatoryHelpDownloadBtn
    val updateMandatoryHelpEmailBtn get() = bundle.updateMandatoryHelpEmailBtn
    val updateMandatoryStepDownload get() = bundle.updateMandatoryStepDownload
    val updateMandatoryStepInstall get() = bundle.updateMandatoryStepInstall
    val updateMandatoryChangelogTitle get() = bundle.updateMandatoryChangelogTitle
    val updateMandatoryErrorNetwork get() = bundle.updateMandatoryErrorNetwork
    val updateMandatoryErrorCorrupt get() = bundle.updateMandatoryErrorCorrupt
    val updateMandatoryHelpOpenBtn get() = bundle.updateMandatoryHelpOpenBtn
    val updateMandatoryHelpClose get() = bundle.updateMandatoryHelpClose
    val updateMandatoryHelpOpenWeb get() = bundle.updateMandatoryHelpOpenWeb
    val updateSimpleHeadline get() = bundle.updateSimpleHeadline
    val updateMandatoryHeadline get() = bundle.updateMandatoryHeadline
    val updateAutoFlowHint get() = bundle.updateAutoFlowHint
    val updateReadyShort get() = bundle.updateReadyShort
    val updateRetry get() = bundle.updateRetry
    val updateHelpExpand get() = bundle.updateHelpExpand

    fun updateOptionalHeadline(version: String): String = String.format(bundle.updateOptionalHeadlineFmt, version)

    fun updateApkSizeMb(bytes: Long): String =
        String.format(bundle.updateApkSizeFmt, bytes / (1024f * 1024f))

    fun updateMandatoryVersionChip(version: String): String =
        String.format(bundle.updateMandatoryVersionChipFmt, version)

    val reply get() = bundle.reply
    val replyingTo get() = bundle.replyingTo
    val replyJumpMissing get() = bundle.replyJumpMissing
    val copied get() = bundle.copied
    val refreshChats get() = bundle.refreshChats
    val someoneTyping get() = bundle.someoneTyping
    val syncedRealtime get() = bundle.syncedRealtime
    val waitingNetwork get() = bundle.waitingNetwork
    val offlineShowingCache get() = bundle.offlineShowingCache
    val cacheStorageTitle get() = bundle.cacheStorageTitle
    val cacheAvatarsHint get() = bundle.cacheAvatarsHint
    val cacheCategoryChats get() = bundle.cacheCategoryChats
    val cacheCategoryPhotos get() = bundle.cacheCategoryPhotos
    val cacheCategoryVideos get() = bundle.cacheCategoryVideos
    val cacheCategoryAudio get() = bundle.cacheCategoryAudio
    val cacheCategoryFiles get() = bundle.cacheCategoryFiles
    val cacheCategoryOther get() = bundle.cacheCategoryOther
    val cacheClearCategory get() = bundle.cacheClearCategory
    val cacheClearAll get() = bundle.cacheClearAll
    val cacheClearAllTitle get() = bundle.cacheClearAllTitle
    val cacheClearAllBody get() = bundle.cacheClearAllBody
    val cacheClearConfirmTitle get() = bundle.cacheClearConfirmTitle
    val cacheClearAction get() = bundle.cacheClearAction
    val cacheCleared get() = bundle.cacheCleared
    val assistixExport get() = bundle.assistixExport
    val assistixExportEmpty get() = bundle.assistixExportEmpty
    val assistixDeleteHistory get() = bundle.assistixDeleteHistory
    val assistixDeleteHistoryTitle get() = bundle.assistixDeleteHistoryTitle
    val assistixDeleteHistoryBody get() = bundle.assistixDeleteHistoryBody
    val assistixNewChat get() = bundle.assistixNewChat
    val assistixThreadsEmpty get() = bundle.assistixThreadsEmpty
    val newChannel get() = bundle.newChannel
    val channelTitle get() = bundle.channelTitle
    val channelNeedTitle get() = bundle.channelNeedTitle
    val channelCreateFailed get() = bundle.channelCreateFailed
    val newChannelHint get() = bundle.newChannelHint
    val createChannel get() = bundle.createChannel
    val searchTabUsers get() = bundle.searchTabUsers
    val searchTabChannels get() = bundle.searchTabChannels
    val searchTabMessages get() = bundle.searchTabMessages
    val whatsNewTitle get() = bundle.whatsNewTitle
    val whatsNewOk get() = bundle.whatsNewOk
    val whatsNew112Title get() = bundle.whatsNew112Title
    val whatsNew112Bullets get() = bundle.whatsNew112Bullets
    val whatsNew148Bullets get() = bundle.whatsNew148Bullets
    val channelNick get() = bundle.channelNick
    val channelNickHint get() = bundle.channelNickHint
    val channelDescription get() = bundle.channelDescription
    val channelNeedNick get() = bundle.channelNeedNick
    val channelSubscribe get() = bundle.channelSubscribe
    val channelUnsubscribe get() = bundle.channelUnsubscribe
    val channelProfile get() = bundle.channelProfile
    val channelEditTitle get() = bundle.channelEditTitle
    val channelEditSave get() = bundle.channelEditSave
    val channelEditAvatar get() = bundle.channelEditAvatar
    val channelAvatarUpdated get() = bundle.channelAvatarUpdated
    val channelSaved get() = bundle.channelSaved
    val channelVerified get() = bundle.channelVerified

    val channelVerifiedTooltip get() = bundle.channelVerifiedTooltip

    val channelOfficialSubscribeBody get() = bundle.channelOfficialSubscribeBody

    val channelOfficialSubscribeBanner get() = bundle.channelOfficialSubscribeBanner

    val later get() = bundle.later

    fun channelSubscribersFmt(count: Int): String = bundle.channelSubscribersFmt.format(count)

    fun channelPostsFmt(count: Int): String = bundle.channelPostsFmt.format(count)

    fun channelPollsFmt(count: Int): String = bundle.channelPollsFmt.format(count)

    fun channelOpensFmt(count: Int): String = bundle.channelOpensFmt.format(count)

    fun channelViewsFmt(count: Int): String = bundle.channelViewsFmt.format(count)

    val channelTranslatedBadge get() = bundle.channelTranslatedBadge
    val channelPostPlaceholder get() = bundle.channelPostPlaceholder
    val channelPostPublish get() = bundle.channelPostPublish
    val channelPostPublished get() = bundle.channelPostPublished
    val channelPostAddImage get() = bundle.channelPostAddImage
    val channelPostImageAttached get() = bundle.channelPostImageAttached
    val channelSearchPosts get() = bundle.channelSearchPosts

    val channelSearchPostsHint get() = bundle.channelSearchPostsHint

    val channelPostsNoResults get() = bundle.channelPostsNoResults

    val channelShareTitle get() = bundle.channelShareTitle

    val channelShareCopyLink get() = bundle.channelShareCopyLink

    val channelShareToChat get() = bundle.channelShareToChat

    val channelShareMessageCta get() = bundle.channelShareMessageCta

    val channelLinkSent get() = bundle.channelLinkSent

    val channelShareNoChats get() = bundle.channelShareNoChats

    val channelOpenFeed get() = bundle.channelOpenFeed

    val channelsOnlyFilter get() = bundle.channelsOnlyFilter

    val channelLike get() = bundle.channelLike

    val channelMembersAdminOnly get() = bundle.channelMembersAdminOnly
    val mediaViewerSave get() = bundle.mediaViewerSave
    val mediaViewerSavedGallery get() = bundle.mediaViewerSavedGallery
    fun mediaViewerCounterFmt(current: Int, total: Int): String = bundle.mediaViewerCounterFmt.format(current, total)

    fun cacheTotalFmt(size: String): String = String.format(bundle.cacheTotalFmt, size)

    fun cacheClearConfirmBody(category: String): String = String.format(bundle.cacheClearConfirmBodyFmt, category)

    fun assistixExportedFmt(path: String): String = String.format(bundle.assistixExportedFmt, path)

    fun assistixRateRemainingFmt(remaining: Int, limit: Int): String =
        String.format(bundle.assistixRateRemainingFmt, remaining, limit)

    fun assistixTokensUsedFmt(used: Int, limit: Int): String =
        String.format(bundle.assistixTokensUsedFmt, used, limit)

    fun assistixTokensResetFmt(hours: Int, minutes: Int): String =
        String.format(bundle.assistixTokensResetFmt, hours, minutes)

    fun folderDeleteConfirmFmt(name: String): String = String.format(bundle.folderDeleteConfirmFmt, name)

    val fabMenuTitle get() = bundle.fabMenuTitle
    val fabMenuSubtitle get() = bundle.fabMenuSubtitle
    val fabSectionChats get() = bundle.fabSectionChats
    val fabSectionTools get() = bundle.fabSectionTools
    val fabSectionMore get() = bundle.fabSectionMore
    val fabNewDmHint get() = bundle.fabNewDmHint
    val fabNewGroupHint get() = bundle.fabNewGroupHint
    val fabChannelHint get() = bundle.fabChannelHint
    val fabPollHint get() = bundle.fabPollHint
    val fabGroupCallHint get() = bundle.fabGroupCallHint
    val fabAssistixHint get() = bundle.fabAssistixHint
    val fabMarkAllHint get() = bundle.fabMarkAllHint
    val fabRefreshHint get() = bundle.fabRefreshHint
    val createPoll get() = bundle.createPoll
    val pollQuestion get() = bundle.pollQuestion
    val pollOptions get() = bundle.pollOptions
    val pollAllowMultiple get() = bundle.pollAllowMultiple
    val pollSend get() = bundle.pollSend
    val pollVote get() = bundle.pollVote
    val pickGroupForPoll get() = bundle.pickGroupForPoll
    val groupCall get() = bundle.groupCall
    val groupCallBetaHint get() = bundle.groupCallBetaHint
    val groupCallStarted get() = bundle.groupCallStarted
    val ringbackTone get() = bundle.ringbackTone
    val callEncrypted get() = bundle.callEncrypted
    val callRelay get() = bundle.callRelay
    val callReconnecting get() = bundle.callReconnecting
    val onboardTextSizeHint get() = bundle.onboardTextSizeHint
    val onboardAutoDownloadHint get() = bundle.onboardAutoDownloadHint
    val onboardAssistixModel get() = bundle.onboardAssistixModel
    val onboardSttOffline get() = bundle.onboardSttOffline
    val pinChat get() = bundle.pinChat
    val unpinChat get() = bundle.unpinChat
    val muteChat get() = bundle.muteChat
    val unmuteChat get() = bundle.unmuteChat
    val jumpToUnread get() = bundle.jumpToUnread
    val searchInChat get() = bundle.searchInChat
    val searchMessagesHint get() = bundle.searchMessagesHint
    val chatSearchFilterAll get() = bundle.chatSearchFilterAll
    val chatSearchFilterText get() = bundle.chatSearchFilterText
    val chatSearchFilterMedia get() = bundle.chatSearchFilterMedia
    val chatSearchFilterLinks get() = bundle.chatSearchFilterLinks
    val chatSearchFilterVoice get() = bundle.chatSearchFilterVoice
    val chatSearchNoResults get() = bundle.chatSearchNoResults
    val callNetworkChecking get() = bundle.callNetworkChecking
    val callNetworkGood get() = bundle.callNetworkGood
    val callNetworkFair get() = bundle.callNetworkFair
    val callNetworkPoor get() = bundle.callNetworkPoor
    val callAudioProcessingHint get() = bundle.callAudioProcessingHint
    val groupCallWaiting get() = bundle.groupCallWaiting
    val groupCallJoining get() = bundle.groupCallJoining
    val groupCallInRoom get() = bundle.groupCallInRoom
    val msgContextSelect get() = bundle.msgContextSelect
    fun callNetworkLabel(bars: Int): String =
        when {
            bars >= 4 -> callNetworkGood
            bars >= 2 -> callNetworkFair
            bars >= 1 -> callNetworkPoor
            else -> callNetworkChecking
        }
    val markAllRead get() = bundle.markAllRead
    val filterAll get() = bundle.filterAll
    val filterUnread get() = bundle.filterUnread
    val chatsEmptyTitle get() = bundle.chatsEmptyTitle
    val chatsEmptyBody get() = bundle.chatsEmptyBody
    val chatsEmptyAction get() = bundle.chatsEmptyAction
    val activeSessions get() = bundle.activeSessions
    val revokeSession get() = bundle.revokeSession
    val currentSession get() = bundle.currentSession
    val noOtherSessions get() = bundle.noOtherSessions
    val devicesSection get() = bundle.devicesSection
    val linkWebConnect get() = bundle.linkWebConnect
    val scanQrLinkWeb get() = bundle.scanQrLinkWeb
    val scanQrLinkHint get() = bundle.scanQrLinkHint
    val scanQrAim get() = bundle.scanQrAim
    val scanQrMinimalHint get() = bundle.scanQrMinimalHint
    val scanQrTitle get() = bundle.scanQrTitle
    val scanQrInstruction get() = bundle.scanQrInstruction
    val scanQrFlashlight get() = bundle.scanQrFlashlight
    val scanQrFound get() = bundle.scanQrFound
    val cameraRequiredForQr get() = bundle.cameraRequiredForQr
    val linkWebApproved get() = bundle.linkWebApproved
    val linkQrInvalid get() = bundle.linkQrInvalid
    val scanAgain get() = bundle.scanAgain
    val chatAccent get() = bundle.chatAccent
    val chatAccentDefault get() = bundle.chatAccentDefault
    val showOnboardingAgain get() = bundle.showOnboardingAgain
    val onboardBulletChats get() = bundle.onboardBulletChats
    val onboardBulletCalls get() = bundle.onboardBulletCalls
    val onboardBulletVoice get() = bundle.onboardBulletVoice
    val onboardOtherInSettings get() = bundle.onboardOtherInSettings
    val onboardPermNotifTitle get() = bundle.onboardPermNotifTitle
    val onboardPermNotifBody get() = bundle.onboardPermNotifBody
    val onboardPermMicTitle get() = bundle.onboardPermMicTitle
    val onboardPermMicBody get() = bundle.onboardPermMicBody
    val onboardPermCameraTitle get() = bundle.onboardPermCameraTitle
    val onboardPermCameraBody get() = bundle.onboardPermCameraBody
    val onboardPermMediaTitle get() = bundle.onboardPermMediaTitle
    val onboardPermMediaBody get() = bundle.onboardPermMediaBody
    val onboardPermAllow get() = bundle.onboardPermAllow
    val onboardPermLater get() = bundle.onboardPermLater
    val onboardPermGranted get() = bundle.onboardPermGranted
    val searchTabAssistix get() = bundle.searchTabAssistix
    val pulseTitle get() = bundle.pulseTitle
    val pulseSubtitle get() = bundle.pulseSubtitle
    val pulseAiSummary get() = bundle.pulseAiSummary
    val pulseUnreadSection get() = bundle.pulseUnreadSection
    val pulseProtoSection get() = bundle.pulseProtoSection
    val pulseSavedSection get() = bundle.pulseSavedSection
    val pulseAllClear get() = bundle.pulseAllClear
    val protoLinkDiscuss get() = bundle.protoLinkDiscuss
    val chatPulse get() = bundle.chatPulse
    val chatPulseHint get() = bundle.chatPulseHint
    val chatPulseEmpty get() = bundle.chatPulseEmpty
    val chatPulseInputHint get() = bundle.chatPulseInputHint
    val languageBuddyOriginal get() = bundle.languageBuddyOriginal
    val deviceGeoFmt get() = bundle.deviceGeoFmt
    val connectivityVpnTitle get() = bundle.connectivityVpnTitle
    val connectivityVpnBody get() = bundle.connectivityVpnBody
    val connectivityForeignTitle get() = bundle.connectivityForeignTitle
    val connectivityForeignBody get() = bundle.connectivityForeignBody
    val connectivitySlowTitle get() = bundle.connectivitySlowTitle
    val connectivitySlowBody get() = bundle.connectivitySlowBody
    val connectivityVpnForeignTitle get() = bundle.connectivityVpnForeignTitle
    val connectivityVpnForeignBody get() = bundle.connectivityVpnForeignBody
    val connectivityForeignSlowTitle get() = bundle.connectivityForeignSlowTitle
    val connectivityForeignSlowBody get() = bundle.connectivityForeignSlowBody
    val messageQueuedOffline get() = bundle.messageQueuedOffline
    val updateStayOnScreenTitle get() = bundle.updateStayOnScreenTitle
    val updateStayOnScreenBody get() = bundle.updateStayOnScreenBody
    val updateInstallVpnHintTitle get() = bundle.updateInstallVpnHintTitle
    val updateInstallVpnHintBody get() = bundle.updateInstallVpnHintBody
    val loginAlertTitle get() = bundle.loginAlertTitle
    val shareIntoProto get() = bundle.shareIntoProto
    val widgetQuickChatLabel get() = bundle.widgetQuickChatLabel
    val widgetQuickChatDesc get() = bundle.widgetQuickChatDesc
}
